// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExchangeSDK is an autogenerated mock type for the ExchangeSDK type
type ExchangeSDK struct {
	mock.Mock
}

// GetPrices provides a mock function with given fields: symbols
func (_m *ExchangeSDK) GetPrices(symbols []string) (map[string]float64, error) {
	ret := _m.Called(symbols)

	var r0 map[string]float64
	if rf, ok := ret.Get(0).(func([]string) map[string]float64); ok {
		r0 = rf(symbols)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(symbols)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
